name: CI/CD Spring Boot App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Create app folder on remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/ec2-user/app

      - name: Copy JAR to remote server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: target/FootballClub-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/app/

      - name: Restart Spring Boot app on remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            pkill -f 'java -jar FootballClub-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar /home/ec2-user/app/FootballClub-0.0.1-SNAPSHOT.jar > /home/ec2-user/app/app.log 2>&1 &
